{
  searchProducts {
    hits {
      id
      name
      price
      images {
        src
        height
        width
        __typename
      }
      sku
      slug
      stockQuantity
    }
  }
}
